stages:
  - build
  - assemble
  - scan
  - publish
  - deploy
  - merge

variables:
  DOCKER_IMAGE: "dulno-app"
  KUBERNETES_RESOURCE: "deployment/dulno-app-deployment"
  STAGING_SERVER_NAME: "10.96.0.20"
  PRODUCTION_SERVER_NAME: "app.dulno.com"

include:
  - project: 'dulno/dulno-template'
    file: '/scan/scan-template.yml'
  - project: 'dulno/dulno-template'
    file: '/merge/merge-template.yml'

build_android:
  stage: build
  image: instrumentisto/flutter:3.32.5-androidsdk35-r0
  before_script:
    - echo $ANDROID_KEYSTORE_CONTENT | base64 -d > android/app/keystore.jks
  script:
    - yes | flutter doctor --android-licenses || true
    - flutter pub run flutter_native_splash:create
    - flutter build appbundle --release --obfuscate --split-debug-info=build/debug-info
    - mv build/app/outputs/bundle/release/app-release.aab android/dulno.aab
  artifacts:
    paths:
      - android/dulno.aab
    expire_in: 1 day
  when: manual

build_web_staging:
  stage: build
  image: ghcr.io/cirruslabs/flutter:3.32.4
  script:
    - flutter build web --release --dart-define=ENVIRONMENT=STAGING
  artifacts:
    paths:
      - build/web
    expire_in: 1 day
  only:
    - dev

build_web_production:
  stage: build
  image: ghcr.io/cirruslabs/flutter:3.32.4
  script:
    - flutter build web --release --dart-define=ENVIRONMENT=PRODUCTION
  artifacts:
    paths:
      - build/web
    expire_in: 1 day
  only:
    - main

assemble_staging:
  stage: assemble
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  dependencies:
    - build_web_staging
  before_script:
    - echo "{\"auths\":{\"$STAGING_DOCKER_REGISTRY\":{\"username\":\"$STAGING_DOCKER_USERNAME\",\"password\":\"$STAGING_DOCKER_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - |
      /kaniko/executor \
        --context "$CI_PROJECT_DIR" \
        --dockerfile "$CI_PROJECT_DIR/web/Dockerfile" \
        --build-arg DOCKER_REGISTRY="$STAGING_DOCKER_REGISTRY" \
        --build-arg SERVER_NAME="$STAGING_SERVER_NAME" \
        --destination "$STAGING_DOCKER_REGISTRY/$DOCKER_IMAGE:test" \
  only:
    - dev

assemble_production:
  stage: assemble
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  dependencies:
    - build_web_production
  before_script:
    - echo "{\"auths\":{\"$PRODUCTION_DOCKER_REGISTRY\":{\"username\":\"$PRODUCTION_DOCKER_USERNAME\",\"password\":\"$PRODUCTION_DOCKER_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - |
      /kaniko/executor \
        --context "$CI_PROJECT_DIR" \
        --dockerfile "$CI_PROJECT_DIR/web/Dockerfile" \
        --build-arg DOCKER_REGISTRY="$PRODUCTION_DOCKER_REGISTRY" \
        --build-arg SERVER_NAME="$PRODUCTION_SERVER_NAME" \
        --destination "$PRODUCTION_DOCKER_REGISTRY/$DOCKER_IMAGE:test" \
  only:
    - main

scan_container_staging:
  stage: scan
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  dependencies: []
  variables:
    TRIVY_USERNAME: $STAGING_DOCKER_USERNAME
    TRIVY_PASSWORD: $STAGING_DOCKER_PASSWORD
  script:
    - trivy image --download-db-only --no-progress --cache-dir .trivycache/
    - trivy image "$STAGING_DOCKER_REGISTRY/$DOCKER_IMAGE:test" --ignore-unfixed --scanners vuln --severity HIGH,CRITICAL --exit-code 1 --cache-dir .trivycache/
  cache:
    key: trivy-cache
    paths:
      - .trivycache/
  allow_failure: false
  only:
    - dev

scan_container_production:
  stage: scan
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  dependencies: []
  variables:
    TRIVY_USERNAME: $PRODUCTION_DOCKER_USERNAME
    TRIVY_PASSWORD: $PRODUCTION_DOCKER_PASSWORD
  script:
    - trivy image --download-db-only --no-progress --cache-dir .trivycache/
    - trivy image "$PRODUCTION_DOCKER_REGISTRY/$DOCKER_IMAGE:test" --ignore-unfixed --scanners vuln --severity HIGH,CRITICAL --exit-code 1 --cache-dir .trivycache/
  cache:
    key: trivy-cache
    paths:
      - .trivycache/
  allow_failure: false
  only:
    - main

publish_staging:
  stage: publish
  image:
    name: quay.io/skopeo/stable:latest
    entrypoint: [""]
  dependencies: []
  before_script:
    - skopeo login --username "$STAGING_DOCKER_USERNAME" --password "$STAGING_DOCKER_PASSWORD" $STAGING_DOCKER_REGISTRY
  script:
    - |
      skopeo copy \
        docker://${STAGING_DOCKER_REGISTRY}/${DOCKER_IMAGE}:test \
        docker://${STAGING_DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest
  only:
    - dev

publish_production:
  stage: publish
  image:
    name: quay.io/skopeo/stable:latest
    entrypoint: [""]
  dependencies: []
  before_script:
    - skopeo login --username "$PRODUCTION_DOCKER_USERNAME" --password "$PRODUCTION_DOCKER_PASSWORD" $PRODUCTION_DOCKER_REGISTRY
  script:
    - |
      skopeo copy \
        docker://${PRODUCTION_DOCKER_REGISTRY}/${DOCKER_IMAGE}:test \
        docker://${PRODUCTION_DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest
  only:
    - main

deploy_staging:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  dependencies: []
  before_script:
    - mkdir -p ~/.kube
    - echo "$STAGING_KUBERNETES_CONFIGURATION" > ~/.kube/config
  script:
    - kubectl rollout restart $KUBERNETES_RESOURCE
    - kubectl rollout status $KUBERNETES_RESOURCE
  only:
    - dev

deploy_production:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  dependencies: []
  before_script:
    - mkdir -p ~/.kube
    - echo "$PRODUCTION_KUBERNETES_CONFIGURATION" > ~/.kube/config
  script:
    - kubectl rollout restart $KUBERNETES_RESOURCE
    - kubectl rollout status $KUBERNETES_RESOURCE
  only:
    - main
