// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKtTo4eVx6JvOxBwlGmzff7BA97RZ9WFc',
    appId: '1:1057662416151:android:5f0b9b670c6160b9897352',
    messagingSenderId: '1057662416151',
    projectId: 'dulno-staging',
    storageBucket: 'dulno-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM4n2wGis8D68TQsv0aA7JIQwk2aLdJMk',
    appId: '1:1057662416151:ios:a461999e687dcf46897352',
    messagingSenderId: '1057662416151',
    projectId: 'dulno-staging',
    storageBucket: 'dulno-staging.firebasestorage.app',
    androidClientId: '1057662416151-lddt6vjrkc73qb7uasu1uhda2t0v0nm8.apps.googleusercontent.com',
    iosClientId: '1057662416151-ucq560kpcjs7225v11upj1d2imsf1gns.apps.googleusercontent.com',
    iosBundleId: 'com.dulno.app',
  );
}
